START TRANSACTION;

INSERT INTO articles
(id, title, abstract, body, publication_year, author_id)
VALUES

(1,
 'Attention Mechanisms for Efficient Neural Language Modeling',
 'This paper investigates efficient attention mechanisms for neural language models and proposes a sparse attention strategy that reduces computational complexity while preserving language modeling performance.',
 'Transformer-based language models rely heavily on self-attention, which introduces substantial computational and memory costs for long sequences. We investigate several sparse attention patterns and propose an adaptive mechanism that dynamically selects relevant tokens. Experiments on multiple language modeling benchmarks demonstrate that the proposed approach substantially reduces computation while maintaining competitive perplexity and downstream task performance.',
 2021, 1),

(2,
 'A Survey of Representation Learning in Deep Neural Networks',
 'We provide a comprehensive survey of representation learning techniques, covering supervised, self-supervised, contrastive, and generative approaches.',
 'Learning useful representations is a central problem in modern machine learning. This paper reviews major approaches to representation learning and analyzes their advantages and limitations. We organize existing methods according to their supervision requirements, architecture, optimization objectives, and transferability. The survey also identifies several open challenges involving robustness, interpretability, and efficient adaptation.',
 2020, 2),

(3,
 'Contrastive Learning for Visual Representation',
 'This work presents a contrastive learning framework for learning visual representations without requiring large amounts of labeled data.',
 'We propose a contrastive representation learning framework that encourages semantically similar images to have nearby embeddings while separating unrelated examples. The method uses augmented views of images as positive pairs and a large set of negative examples. Extensive experiments show that the learned representations transfer effectively to image classification and retrieval tasks.',
 2021, 3),

(4,
 'Robust Optimization of Transformer Models',
 'This paper studies optimization techniques that improve the robustness of Transformer models under distribution shifts and noisy training data.',
 'Transformer models can achieve excellent performance on benchmark datasets but may degrade significantly when the data distribution changes. We investigate robust optimization objectives based on adversarial perturbations and uncertainty-aware regularization. Results indicate that combining these objectives improves generalization across several out-of-distribution evaluation settings.',
 2022, 4),

(5,
 'Self-Supervised Learning for Natural Language Understanding',
 'We study self-supervised objectives for improving natural language understanding without relying on extensive human annotation.',
 'Self-supervised learning has enabled the development of large-scale language models from unlabeled corpora. This paper compares several pretraining objectives and analyzes their effect on downstream natural language understanding. Our experiments suggest that combining token-level prediction with sentence-level objectives provides improved transfer performance across classification and reasoning tasks.',
 2020, 5),

(6,
 'Efficient Fine-Tuning of Large Language Models',
 'We introduce an efficient parameter-efficient fine-tuning method that substantially reduces the memory requirements of adapting large language models.',
 'Fine-tuning large language models can require significant computational resources. We investigate low-rank adaptation and selective parameter updates as alternatives to full model fine-tuning. The proposed approach achieves comparable performance while updating only a small fraction of model parameters, making large language models more accessible in resource-constrained environments.',
 2022, 6),

(7,
 'Graph Neural Networks for Citation Prediction',
 'This paper proposes a graph neural network architecture for predicting citation relationships between scientific articles.',
 'Scientific literature naturally forms a graph in which papers are connected through citation relationships. We develop a graph neural network that jointly models article representations and citation structure. Evaluation on a collection of scientific publications demonstrates that graph-based representations improve citation prediction compared with traditional text-only baselines.',
 2021, 7),

(8,
 'Knowledge Graphs for Scientific Literature',
 'We investigate knowledge graph representations for organizing and retrieving scientific literature.',
 'Scientific publications contain complex relationships among authors, concepts, institutions, and references. We construct a knowledge graph that represents these relationships and develop retrieval algorithms that exploit graph structure. Experiments show that knowledge-aware retrieval improves the relevance of results for multi-hop scientific queries.',
 2022, 8),

(9,
 'Neural Information Retrieval with Dense Representations',
 'This work explores dense neural representations for information retrieval and compares them with traditional lexical retrieval methods.',
 'Traditional information retrieval systems rely heavily on lexical matching. Dense retrieval instead represents queries and documents using continuous vectors. We investigate several dense retrieval architectures and training objectives. Results demonstrate that dense retrieval can substantially improve semantic matching, particularly for queries containing terminology different from the retrieved documents.',
 2021, 9),

(10,
 'Semantic Search for Academic Documents',
 'We present a semantic search system designed specifically for retrieving relevant academic documents from large scientific collections.',
 'Academic search requires understanding technical terminology and relationships between concepts. We develop a semantic retrieval architecture that combines dense document embeddings with lexical filtering. The resulting system improves retrieval quality across several academic search tasks and provides more relevant results for conceptually related queries.',
 2023, 10),

(11,
 'Retrieval-Augmented Generation for Question Answering',
 'This paper investigates retrieval-augmented generation as a method for improving factual question answering with external knowledge.',
 'Large language models may generate plausible but unsupported information when answering factual questions. We investigate retrieval-augmented generation, where relevant documents are retrieved before generating an answer. Experiments show that grounding generation in retrieved evidence improves factual accuracy and reduces unsupported statements.',
 2023, 1),

(12,
 'Evaluating Hallucination in Large Language Models',
 'We introduce an evaluation framework for measuring factual hallucination in large language models across different question answering settings.',
 'Hallucination remains an important limitation of generative language models. We define several metrics for identifying unsupported claims and evaluate language models under controlled conditions. Our findings indicate that hallucination rates depend strongly on question difficulty, model scale, and access to external information.',
 2023, 2),

(13,
 'Uncertainty Estimation for Neural Text Generation',
 'This study examines methods for estimating uncertainty during neural text generation and investigates their relationship with factual reliability.',
 'Reliable uncertainty estimates can help identify generated responses that require verification. We compare probabilistic and sampling-based uncertainty measures for language generation. Experiments show that token-level uncertainty and response-level disagreement provide useful signals for detecting unreliable generations.',
 2022, 3),

(14,
 'Improving Long Context Reasoning in Language Models',
 'We investigate methods for improving language model reasoning over documents containing thousands of tokens.',
 'Long-context reasoning presents both computational and representational challenges. We propose a hierarchical processing strategy that divides long documents into semantically meaningful segments before integrating their representations. Experiments on document question answering and summarization demonstrate improvements over standard full-context processing.',
 2024, 4),

(15,
 'Parameter-Efficient Adaptation of Transformer Networks',
 'This paper provides an empirical comparison of parameter-efficient adaptation techniques for Transformer architectures.',
 'We compare low-rank adaptation, adapter layers, prompt tuning, and selective parameter updating. Across multiple language understanding benchmarks, parameter-efficient approaches achieve performance close to full fine-tuning while requiring substantially fewer trainable parameters.',
 2022, 5),

(16,
 'Learning Diverse Responses from Language Models',
 'We study methods for increasing the diversity of generated responses while maintaining relevance and correctness.',
 'Language models often produce highly similar outputs when responding to the same prompt. We propose a training objective that explicitly encourages semantic diversity among multiple generated responses. Experiments demonstrate increased lexical and semantic diversity without substantial degradation in response quality.',
 2024, 6),

(17,
 'Measuring Diversity in Neural Text Generation',
 'We present a systematic analysis of metrics for measuring diversity in neural text generation.',
 'Evaluating diversity requires distinguishing meaningful variation from irrelevant changes. We analyze lexical diversity, n-gram overlap, embedding similarity, and distributional metrics. Our experiments reveal that no single metric fully captures response diversity and recommend combining complementary measures.',
 2023, 7),

(18,
 'Semantic Similarity Metrics for Generated Text',
 'This work evaluates semantic similarity metrics for comparing machine-generated text and human-written references.',
 'Automatic evaluation of generated text frequently relies on surface-level similarity measures. We compare lexical metrics with embedding-based semantic similarity measures across summarization, translation, and dialogue tasks. Results demonstrate that embedding-based metrics better capture semantic equivalence in many settings.',
 2021, 8),

(19,
 'A Study of Transformer Scaling Laws',
 'We empirically investigate the relationship between model size, dataset size, computational budget, and Transformer performance.',
 'Scaling laws provide useful guidance for allocating computational resources during model training. We evaluate Transformer models across a range of parameter counts and dataset sizes. The observed trends indicate predictable improvements when model capacity and training data are balanced appropriately.',
 2022, 9),

(20,
 'Efficient Training Strategies for Large Neural Networks',
 'This paper investigates optimization and data-loading techniques for reducing the computational cost of training large neural networks.',
 'Training large models requires efficient use of hardware resources. We examine gradient accumulation, mixed precision, activation checkpointing, and optimized data pipelines. Combining these methods substantially reduces memory usage and improves training throughput while preserving model quality.',
 2021, 10),

(21,
 'Neural Summarization with Retrieval Support',
 'We propose a retrieval-supported summarization framework that uses external documents to improve the factual consistency of generated summaries.',
 'Automatic summarization systems may introduce unsupported claims or omit important contextual information. Our method retrieves relevant passages before generating summaries. Experiments on scientific and news datasets show improved factual consistency and coverage compared with standard sequence-to-sequence models.',
 2023, 1),

(22,
 'Factuality Evaluation of Generated Summaries',
 'We introduce a benchmark for evaluating the factual consistency of automatically generated summaries.',
 'We construct a dataset containing human annotations of factual errors in generated summaries. Several automatic evaluation metrics are compared against human judgments. The results highlight weaknesses in lexical-overlap metrics and demonstrate the value of entailment-based evaluation.',
 2023, 2),

(23,
 'Document-Level Scientific Information Extraction',
 'This paper presents a neural system for extracting entities and relationships from scientific publications.',
 'Scientific documents contain structured information distributed across multiple sections. We propose a document-level information extraction model that jointly represents paragraphs, entities, and relations. The approach improves extraction performance on scientific datasets containing complex cross-sentence relationships.',
 2022, 3),

(24,
 'Automated Discovery of Research Topics',
 'We develop an unsupervised framework for identifying emerging research topics from large collections of scientific papers.',
 'Research areas evolve rapidly, making manual topic discovery difficult. Our method combines document embeddings with temporal clustering to identify emerging themes. Evaluation on several years of scientific publications demonstrates that the framework can identify topic transitions and emerging research directions.',
 2024, 4),

(25,
 'Temporal Analysis of Scientific Citation Networks',
 'We analyze the temporal evolution of scientific citation networks and investigate patterns associated with influential publications.',
 'Citation networks evolve as researchers build upon existing findings. We model citation graphs over time and examine structural properties associated with influential articles. The analysis reveals recurring patterns in how new research communities form around emerging topics.',
 2020, 5),

(26,
 'Predicting the Impact of Scientific Publications',
 'This work proposes a machine learning model for predicting future citation impact using textual and graph-based features.',
 'Predicting the future influence of scientific papers can support research discovery and evaluation. We combine article embeddings, author information, and citation graph features in a predictive model. Experiments show that combining textual and structural features provides stronger predictions than either source alone.',
 2021, 6),

(27,
 'Personalized Academic Search Using User Profiles',
 'We present a personalized academic search system that adapts retrieval results to individual research interests.',
 'Researchers often need to search across broad scientific collections while focusing on specific areas. Our system constructs lightweight user interest profiles from search history and selected publications. Personalized ranking improves retrieval relevance compared with generic ranking strategies.',
 2024, 7),

(28,
 'Hybrid Retrieval for Scientific Search',
 'This paper proposes a hybrid retrieval architecture that combines lexical and dense semantic retrieval for scientific documents.',
 'Lexical retrieval provides strong performance for exact terminology, while dense retrieval captures semantic relationships. We combine both approaches using a learned ranking model. Experiments demonstrate consistent improvements across scientific information retrieval benchmarks.',
 2023, 8),

(29,
 'Efficient Vector Search for Large Document Collections',
 'We investigate approximate nearest-neighbor techniques for efficiently searching large collections of document embeddings.',
 'Dense retrieval systems require efficient vector indexing when collections contain millions of documents. We evaluate several approximate nearest-neighbor algorithms and investigate the trade-off between latency, memory consumption, and recall. Our results provide practical recommendations for large-scale semantic search systems.',
 2022, 9),

(30,
 'Benchmarking Academic Information Retrieval Systems',
 'We introduce a benchmark for evaluating information retrieval systems on academic search tasks.',
 'Academic retrieval differs from general web search due to specialized terminology, citation relationships, and long documents. We construct a benchmark covering document retrieval, author discovery, citation prediction, and related-paper recommendation. The benchmark enables systematic comparison of modern retrieval approaches.',
 2024, 10),

(31,
 'Recommending Related Scientific Articles with Graph Embeddings',
 'We propose a graph embedding method for recommending scientific articles based on citation and semantic relationships.',
 'Related-paper recommendation can help researchers navigate large scientific collections. Our model represents articles using both citation neighborhoods and textual embeddings. Evaluation shows that incorporating graph structure improves recommendation quality compared with text-only approaches.',
 2023, 1),

(32,
 'Multi-Modal Representation Learning for Scientific Documents',
 'This paper investigates joint representation learning for scientific text, figures, and tables.',
 'Scientific articles contain information in multiple modalities. We propose a multimodal encoder that combines textual representations with visual representations extracted from figures and tables. Experiments show improvements on document classification and information retrieval tasks.',
 2024, 2),

(33,
 'Interpretable Neural Models for Scientific Text',
 'We study techniques for improving the interpretability of neural models applied to scientific documents.',
 'Interpretability is important when machine learning systems are used to assist scientific research. We investigate attention visualization, feature attribution, and example-based explanations. Human evaluation indicates that combining multiple explanation methods provides researchers with a clearer understanding of model predictions.',
 2021, 3),

(34,
 'Trustworthy Machine Learning for Scientific Applications',
 'This paper examines reliability, robustness, and transparency requirements for machine learning systems used in scientific workflows.',
 'Machine learning systems increasingly support scientific discovery and decision making. We analyze common failure modes involving dataset bias, distribution shifts, uncertainty, and model errors. We propose a framework for evaluating trustworthiness throughout the machine learning lifecycle.',
 2022, 4),

(35,
 'Detecting Bias in Large Language Models',
 'We present an evaluation framework for identifying systematic biases in large language models across diverse prompts and domains.',
 'Large language models may reproduce biases present in their training data. We design controlled experiments for measuring differences in model behavior across demographic and contextual variations. The results demonstrate the importance of evaluating models using multiple prompt templates and diverse datasets.',
 2023, 5),

(36,
 'Model Editing for Knowledge Updating',
 'We investigate methods for modifying specific factual knowledge in pretrained language models without retraining the entire model.',
 'Knowledge stored in pretrained language models can become outdated. Model editing aims to update individual facts while preserving unrelated model behavior. We compare several editing strategies and analyze their locality, generalization, and stability across multiple benchmarks.',
 2023, 6),

(37,
 'Machine Unlearning in Neural Language Models',
 'This paper investigates techniques for removing specific information from trained language models while preserving general model capabilities.',
 'Machine unlearning seeks to remove the influence of selected training information from a trained model. We study several unlearning objectives based on gradient optimization and preference learning. Evaluation focuses on both forgetting effectiveness and retention of unrelated capabilities.',
 2024, 7),

(38,
 'Evaluating Knowledge Removal in Generative Models',
 'We propose an evaluation framework for measuring whether targeted information has been effectively removed from generative models.',
 'Evaluating unlearning requires measuring both the removal of targeted knowledge and preservation of unrelated behavior. We introduce evaluation procedures based on direct questioning, paraphrased prompts, and indirect knowledge probes. Results show that conventional evaluations may underestimate residual model knowledge.',
 2024, 8),

(39,
 'Latent Representations and Knowledge in Language Models',
 'We investigate how factual information is encoded in the latent representations of Transformer-based language models.',
 'Understanding where knowledge is represented inside language models may enable more precise model editing and unlearning. We analyze hidden representations across multiple Transformer layers and identify regions associated with specific factual concepts. The findings suggest that knowledge is distributed across multiple layers rather than stored in a single localized representation.',
 2024, 9),

(40,
 'A Unified Framework for Scientific Literature Understanding',
 'We present a unified framework combining retrieval, representation learning, graph modeling, and language generation for scientific literature understanding.',
 'Scientific literature analysis requires integrating information from documents, citations, authors, and semantic relationships. We propose a unified architecture combining dense retrieval, graph representations, and language models. Experiments across retrieval, recommendation, summarization, and citation prediction tasks demonstrate the benefits of jointly modeling these sources of information.',
 2025, 10);

INSERT INTO article_citations (citing_article_id, cited_article_id) VALUES

(4, 1),
(4, 2),
(5, 2),
(5, 3),
(6, 1),
(6, 4),
(6, 5),
(7, 2),
(7, 8),
(7, 9),
(8, 2),
(8, 7),
(8, 9),
(8, 10),
(9, 2),
(9, 3),
(9, 10),
(10, 8),
(10, 9),
(10, 2),
(11, 9),
(11, 10),
(11, 6),
(12, 5),
(12, 11),
(13, 12),
(13, 11),
(14, 1),
(14, 6),
(14, 11),
(15, 6),
(15, 4),
(16, 6),
(16, 13),
(16, 15),
(17, 16),
(17, 18),
(18, 2),
(18, 9),
(19, 1),
(19, 4),
(20, 6),
(20, 19),
(20, 15),
(21, 11),
(21, 14),
(22, 12),
(22, 18),
(22, 21),
(23, 8),
(23, 10),
(24, 8),
(24, 23),
(25, 7),
(25, 8),
(26, 7),
(26, 25),
(26, 19),
(27, 10),
(27, 24),
(28, 9),
(28, 10),
(28, 18),
(29, 9),
(29, 28),
(30, 10),
(30, 25),
(30, 26),
(30, 28),
(31, 7),
(31, 9),
(31, 26),
(32, 23),
(32, 18),
(33, 2),
(33, 13),
(34, 4),
(34, 12),
(34, 33),
(35, 12),
(35, 34),
(36, 6),
(36, 13),
(36, 34),
(37, 6),
(37, 15),
(37, 16),
(37, 36),
(38, 12),
(38, 35),
(38, 36),
(38, 37),
(39, 6),
(39, 13),
(39, 16),
(39, 36),
(39, 37),
(39, 38),
(40, 7),
(40, 8),
(40, 9),
(40, 10),
(40, 11),
(40, 21),
(40, 24),
(40, 28),
(40, 31),
(40, 32),
(40, 39);

COMMIT;